#Rvec module main
#(c) Jake Leroux 2021-22 BSD Class 3

require 'matrix'
require 'rspec'
require_relative 'arraygen'
require_relative 'identifier'
require_relative 'rvarray'
require_relative 'positive'
require_relative 'negative'
require_relative 'exp'
require_relative 'dot'
require_relative 'sigmoid'
require_relative 'sigmoid_derivative'
require_relative 'addcorrarr'
require_relative 'subcorrarr'
require_relative 'multicorrarr'
require_relative 'divcorrarr'
require_relative 'errornum'
require_relative 'helpercommands'